import { z } from 'zod';
import { tool } from 'ai';

export const pythonTool = tool({
    description: 'Execute Python code for advanced data analysis or plotting. Use this when SQL is not enough (e.g. forecasting, complex stats).',
    parameters: z.object({
        code: z.string().describe('The Python code to execute. MUST use pandas/matplotlib.'),
        explanation: z.string().describe('Brief explanation of what the code does.'),
    }),
    execute: async ({ code, explanation }: { code: string, explanation: string }) => {
        // Debug logging only in development
        if (process.env.NODE_ENV === 'development') {
            // eslint-disable-next-line no-console
            console.log(`[PYTHON_TOOL] Executing:\n${code}`);
        }

        // Mock Execution
        // In real world: Send to E2B sandbox or Docker container

        // Detect intent by keywords in the code/explanation
        const lowerCode = code.toLowerCase();

        if (lowerCode.includes('plot') || lowerCode.includes('chart')) {
            // Return a visualization object that the frontend understands
            return {
                Type: 'VISUALIZATION',
                Content: explanation,
                Data: {
                    plotType: 'line', // Infer from code (plt.plot vs plt.bar)
                    title: 'Trend Analysis (Generated by Python)',
                    data: [
                        { x: '2025-08', y: 42000 },
                        { x: '2025-09', y: 48000 },
                        { x: '2025-10', y: 51000 },
                        { x: '2025-11', y: 49000 },
                        { x: '2025-12', y: 65000 },
                        { x: '2026-01', y: 58000 },
                    ],
                    xKey: 'x',
                    dataKey: 'y'
                }
            };
        }

        return {
            Type: 'MESSAGE',
            Content: `Executed Python code successfully.\nOutput:\n\`\`\`\nAnalysis Complete. R-Squared: 0.85\nForecast for next month: €62,500\n\`\`\``
        };
    },
});
